jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
          registry: ghcr.io

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.3.0
        with:
          push: true
          tags: ghcr.io/baranselkarakas/vrising-server:${{ github.sha }}
on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build-and-push-container.yaml

